# Copyright 2022, The Johns Hopkins University Applied Physics Laboratory LLC
# All rights reserved.
# Distributed under the terms of the BSD 3-Clause License.
#
# NO WARRANTY, NO LIABILITY. THIS MATERIAL IS PROVIDED “AS IS.” JHU/APL MAKES NO
# REPRESENTATION OR WARRANTY WITH RESPECT TO THE PERFORMANCE OF THE MATERIALS, INCLUDING
# THEIR SAFETY, EFFECTIVENESS, OR COMMERCIAL VIABILITY, AND DISCLAIMS ALL WARRANTIES IN
# THE MATERIAL, WHETHER EXPRESS OR IMPLIED, INCLUDING (BUT NOT LIMITED TO) ANY AND ALL
# IMPLIED WARRANTIES OF PERFORMANCE, MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE,
# AND NON-INFRINGEMENT OF INTELLECTUAL PROPERTY OR OTHER THIRD PARTY RIGHTS. ANY USER OF
# THE MATERIAL ASSUMES THE ENTIRE RISK AND LIABILITY FOR USING THE MATERIAL. IN NO EVENT
# SHALL JHU/APL BE LIABLE TO ANY USER OF THE MATERIAL FOR ANY ACTUAL, INDIRECT,
# CONSEQUENTIAL, SPECIAL OR OTHER DAMAGES ARISING FROM THE USE OF, OR INABILITY TO USE,
# THE MATERIAL, INCLUDING, BUT NOT LIMITED TO, ANY DAMAGES FOR LOST PROFITS.
ORGANISM_ID_1='BAC_1'
ORGANISM_ID_2='BAC_2'
ORGANISM_ID_3='BAC_3'
ORGANISM_ID_4='BAC_4'
ORGANISM_ID_5='BAC_5'
ORGANISM_ID_6='BAC_6'
ORGANISM_ID_7='BAC_7'
ORGANISM_ID_8='BAC_8'
ORGANISM_ID_9='BAC_9'

ORGANISM_NAME_1='ORGANISM-1'
ORGANISM_NAME_2='ORGANISM-2'
ORGANISM_NAME_3='ORGANISM-3'
ORGANISM_NAME_4='ORGANISM-4'
ORGANISM_NAME_5='ORGANISM-5'
ORGANISM_NAME_6='ORGANISM-6'
ORGANISM_NAME_7='ORGANISM-7'
ORGANISM_NAME_8='ORGANISM-8'
ORGANISM_NAME_9='ORGANISM-9'