# Copyright 2022, The Johns Hopkins University Applied Physics Laboratory LLC
# All rights reserved.
# Distributed under the terms of the BSD 3-Clause License.
#
# NO WARRANTY, NO LIABILITY. THIS MATERIAL IS PROVIDED “AS IS.” JHU/APL MAKES NO
# REPRESENTATION OR WARRANTY WITH RESPECT TO THE PERFORMANCE OF THE MATERIALS, INCLUDING
# THEIR SAFETY, EFFECTIVENESS, OR COMMERCIAL VIABILITY, AND DISCLAIMS ALL WARRANTIES IN
# THE MATERIAL, WHETHER EXPRESS OR IMPLIED, INCLUDING (BUT NOT LIMITED TO) ANY AND ALL
# IMPLIED WARRANTIES OF PERFORMANCE, MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE,
# AND NON-INFRINGEMENT OF INTELLECTUAL PROPERTY OR OTHER THIRD PARTY RIGHTS. ANY USER OF
# THE MATERIAL ASSUMES THE ENTIRE RISK AND LIABILITY FOR USING THE MATERIAL. IN NO EVENT
# SHALL JHU/APL BE LIABLE TO ANY USER OF THE MATERIAL FOR ANY ACTUAL, INDIRECT,
# CONSEQUENTIAL, SPECIAL OR OTHER DAMAGES ARISING FROM THE USE OF, OR INABILITY TO USE,
# THE MATERIAL, INCLUDING, BUT NOT LIMITED TO, ANY DAMAGES FOR LOST PROFITS.

declare -A ORGANISM_ID
declare -A ORGANISM_NAME

ORGANISM_ID[1]='Bce'
ORGANISM_ID[2]='Bc-nn'
ORGANISM_ID[3]='Bru'
ORGANISM_ID[4]='Br-nn'
ORGANISM_ID[5]='Brk'
ORGANISM_ID[6]='Bk-nn'

ORGANISM_NAME[1]='Bacillis cereus'
ORGANISM_NAME[2]='Bacillis cereus near neighbor'
ORGANISM_NAME[3]='Brucells abortus'
ORGANISM_NAME[4]='Brucells abortus near neighbor'
ORGANISM_NAME[5]='Burkholderia cepacia'
ORGANISM_NAME[6]='Burkholderia cepacia near neighbor'

